version: "3.8"
services:
  pinger:
    build: .
    volumes:
      - .:/app
    command: python3 ping_contestant_machines.py
    cap_add:
      - NET_RAW

  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: python3 -m http.server 8080
